name: Updated Feature Request
description: For when you know better than me what you want
title: "[Request]"
labels: enhancement
assignees:
  - mnadareski
body:
  - type: markdown
    attributes:
      value: |
        **Before You Submit**
        - Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
        - Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
        - .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're asking for isn't already in another build.
        - Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.
        If none of those apply, then continue...

  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please put a clear and concise description of what the problem is.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Please put a clear and concise description of what you want to happen.
      placeholder: "Example: I think a solution to this could be..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please put a clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Example: Alternatives I've considered include..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Example: We talked about this previously in VGPC, and..."
    validations:
      required: false
