name: Info
description: Something you need to tell me
title: "[Info]"
labels: question
assignees:
  - mnadareski

body:
  - type: markdown
    attributes:
      value: |
        **Before You Submit**
        - Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
        - Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
        - .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're giving information on isn't already in another build.
        - Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.
        If none of those apply, then continue...

  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your information related to one of the dumping programs supported, or something that isn't a bug in the code?
      description: Please put a clear and concise description of what the information is.
      placeholder: "Example: With the latest build of DumpingProgram, it..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Example: We talked about this previously in VGPC, and..."
    validations:
      required: false
