name: Updated Feature Request
description: For when you know better than me what you want
title: "[Request]"
labels: enhancement
assignees:
  - mnadareski
body: 
  - type: markdown
    attributes:
      value: |
        **Before You Submit**
        - Remember to try the [latest WIP build](https://ci.appveyor.com/project/mnadareski/mpf/build/artifacts) to see if the feature already exists.
        - Is it copy protection related? If so, report the issue [here](https://github.com/mnadareski/BurnOutSharp/issues) instead.
        - .NET Core 3.1 and .NET 5.0 have known limitations, so make sure that what you're asking for isn't already in another build.
        - Check [previous issues](https://github.com/SabreTools/MPF/issues) to see if any of those are related to what you're about to ask for.
        If none of those apply, then continue...

  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please put a clear and concise description of what the problem is.
      placeholder: "Example: I'm always frustrated when [...]"
      value: "Example: I'm always frustrated when [...]"
    validations:
      required: true

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
